messages:
  # сообщение если у игрока не будет прав
  no-permission-message:
    - "&#F87373[✘] &7У вас &#F87373нет прав &7на выполнение этой команды!"
  # сообщение о правильном использовании команд
  usage-commands-message:
    - "&6 Команды: "
    - "&f"
    - "&6/vcustomeggs give [игрок] [яичко] [количество] &7- команда что бы выдать яичко"
    - "&f"
    - "&6/vcustomeggs reload &7- команда что бы перезагрузить плагин"
    - "&f"
  # сообщение если игрока не было найдено
  player-not-found-message:
    - "&#F87373[✘] &7Игрок &#F87373не &7найден!"
  # сообщение о выдачем кастомного яичка
  egg-given-message:
    - "&#A7F498[✔] &7Кастомное яичко было &#A7F498выдана &7игроку &6{player}&7!"
  # сообщение если указать не правильно ID
  invalid-item-message:
    - "&#F87373[✘] &7Эй, ты что-то не то написал!"
    - " &8- &7Укажи &#A7F498правильный &6ID &7яйца (например, zombie_egg, mixed_egg)!"
  # сообщение об перезагрузке плагина
  reload-success-message:
    - "&#A7F498[✔] &7Конфигурация &#A7F498успешно &7перезагружена!"
  # сообщение если указать число меньше нуля
  amount-must-be-positive-message:
    - "&#F87373[✘] &7Эй, количество должно быть больше нуля!"
  # сообщение если указать количество яичек больше 64 штук при выдаче
  amount-too-large-message:
    - "&#F87373[✘] &7Слишком много! Максимум &664 &7яйца!"
    - " - &7Выдано &664, &7и не жалуйся!"
  # сообщение если указать буквы вместо числа
  invalid-amount-message:
    - "&#F87373[✘] &7Ты что, буквы вместо числа написал?"

#---------------------------------------------------------------------------------------

eggs:
  zombie_egg:
    material: ZOMBIE_SPAWN_EGG
    name: "&#B481FFКастомное Яйцо"
    lore:
      - ""
      - "&fУникальность:"
      - " &7содержит случайного"
      - " &7моба из списка"
      - ""
      - "  &7Зомби &7- &650%"
      - "  &7Зомби-житель &7- &630%"
      - "  &7Крипер &7- &620%"
      - "  &7Утопленик &7- &610%"
      - ""
    mobs:
      - "ZOMBIE;50"
      - "ZOMBIE_VILLAGER;30"
      - "CREEPER;20"
      - "DROWNED;10"
  mixed_egg:
    material: CREEPER_SPAWN_EGG
    name: "&#F4E898Смешанное Яйцо"
    lore:
      - ""
      - "&fУникальность:"
      - " &7содержит случайного"
      - " &7моба из списка"
      - ""
      - "  &7Зомби &7- &640%"
      - "  &7Скилет &7- &630%"
      - "  &7Крипер &7- &620%"
      - "  &7Визер скелет &7- &610%"
      - ""
    mobs:
      - "ZOMBIE;40"
      - "SKELETON;30"
      - "CREEPER;20"
      - "WITHER_SKELETON;10"
  test:
    material: GHAST_SPAWN_EGG
    name: "&#F4E898Яйцо призыва Железного-голема"
    lore:
      - ""
      - "&fУникальность:"
      - " &7содержит в себе"
      - " &7железного голема!"
      - ""
      - "  &7Железный голем &7- &6100%"
      - ""
    mobs:
      - "IRON_GOLEM;100"